apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: influxdb-jmeter
data:
  load_test: |
    #!/bin/bash -xv
    #Script created to invoke jmeter test script with the worker POD IP addresses
    #Script should be run like: ./load_test "path to the test script in jmx format"
    # jmeter/bin/jmeter -n -t $1 $2 $3
    jmeter/bin/jmeter -n -t $1 -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 jmeter-worker-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'` $2 $3 $4 $5 $6

